#+TITLE: Qrvhh's page

#+NICK: Qrvhh

#+DESCRIPTION: striving for the ultimate minimalist, productive, stable setup - like a piece of paper and a pencil, just digital... GNU/Linux, BSD, Solaris, emacs, light themes, traveling, reading, podcasts, cooking, learning languages, tinkering with old-tech, self-hosting, gym/calisthenics, decluttering/minimalism and occasionally writing

#+AVATAR: https://media.mstdn.social/accounts/avatars/111/348/090/707/184/525/original/0e6f7c7311f19321.png

#+LINK: https://blog.benedekvigh.hu

#+FOLLOW: https://sachachua.com/social.org

* Posts
**
:PROPERTIES:
:ID: 2025-09-25T15:14:00+02:00
:END:

Still figuring out how this timestamp should work...

**
:PROPERTIES:
:ID: 2025-09-25T15:23:30+0200
:LANG: 
:TAGS: 
:CLIENT: org-social.el
:MOOD: 
:END:

I wonder if this works

**
:PROPERTIES:
:ID: 2025-10-01T16:21:57+0200
:LANG: en
:TAGS: 
:CLIENT: org-social.el
:MOOD: curious
:END:

org-social.el 2 is looking awesome! Have to confess, this is the geekiest social I've ever used, but also the one that's the most interesting. Hope more emacs user will consider joining!

**
:PROPERTIES:
:ID: 2025-10-08T14:04:25+0200
:LANG: 
:TAGS: 
:CLIENT: org-social.el
:REPLY_TO: https://andros.dev/static/social.org#2025-10-07T12:04:13+0200
:MOOD: happy
:END:

Awesome, finally got to fix my social.org file! Thank you for this update as well!

**
:PROPERTIES:
:ID: 2025-10-15T08:49:53+0200
:LANG: en
:TAGS: 
:CLIENT: org-social.el
:REPLY_TO: https://codeberg.org/eludom/org-social/raw/branch/main/social.org#2025-10-13T07:40:24-0400
:MOOD: 
:END:

Auto-commit could probably be set up with magit and a hook? I'm also thinking of doing something like that currently, I feel like it should be possible in a relatively simple way. Will post about once I manage to get it up and running.

**
:PROPERTIES:
:ID: 2025-10-15T09:56:26+0200
:LANG: en
:TAGS: test
:CLIENT: org-social.el
:MOOD: 
:END:

Testing out the one-command solution to push changes to my org-social file in one step......

**
:PROPERTIES:
:ID: 2025-10-15T10:25:11+0200
:LANG: en
:TAGS: 
:CLIENT: org-social.el
:REPLY_TO: https://raw.githubusercontent.com/fengbainuo/org-social/refs/heads/main/social.org#2025-10-15T09:56:26+0200
:MOOD: 
:END:

This was done in elisp, which I'm not familiar enough with, so was done using ai. I'm surprised it works, but I'll probably not use it, unless I can write it for myself.

I'm not against /AI-assisted/ coding, but I'd rather not rely on something that's written almost entirely with AI by someone who is not familiar with the language (me in this case).

**
:PROPERTIES:
:ID: 2025-10-17T12:55:12+0200
:LANG: en
:TAGS: 
:CLIENT: org-social.el
:REPLY_TO: https://thesolarprincess.site/social.org#2025-10-16T23:00:00-0300
:MOOD: 
:END:

Welcome! Just checked out your blog, nice to see that it works in eww!

**
:PROPERTIES:
:ID: 2025-10-17T13:19:01+0200
:LANG: en
:TAGS: games pso ps0 
:CLIENT: org-social.el
:MOOD: 🎮
:END:

Started up my old 3DS this week after a long time, and played some Phantasy Star 0 - I can't say I have nostalgia for /this/ game or console in particular, as I've played this game for the first time ever maybe last year, when I also purchased this used console. I *do* however have nostalgia for old games in general, which is probably the reason why I enjoy playing this somewhat clunky sci-fi rpg every once in a while.

Not quite the same as Phantasy Star Online Blue Burst, but for someone like me who commutes a lot, it's a relaxing activity for when I'm too tired to spend the time with doing something productive.
